# Generated by Django 3.2.9 on 2024-05-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incomejson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('is_processed', models.BooleanField(default=None, null=True, verbose_name='Валидация пройдена')),
                ('json', models.JSONField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Входящие JSON',
                'verbose_name_plural': 'Входящие JSON',
            },
        ),
        migrations.CreateModel(
            name='Robo7Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_fio', models.CharField(max_length=255, verbose_name='ФИО пациента')),
                ('analysis', models.CharField(max_length=255, verbose_name='Наименование вида исследования')),
                ('code', models.CharField(max_length=255, verbose_name='ШК')),
                ('tray_num', models.IntegerField(default=0, null=True, verbose_name='Назначенный лоток')),
                ('is_tray_assigned', models.BooleanField(default=None, null=True, verbose_name='Лоток назначен')),
                ('is_validated', models.BooleanField(default=None, null=True, verbose_name='Валидация пройдена')),
                ('is_sent', models.BooleanField(default=None, null=True, verbose_name='Отправлено на прибор')),
                ('is_complete', models.BooleanField(default=None, null=True, verbose_name='Выполнено')),
                ('is_filename', models.BooleanField(default=None, null=True, verbose_name='Сформировано имя файла')),
                ('filename', models.CharField(default=None, max_length=255, null=True, verbose_name='Имя файла')),
                ('filenameok', models.CharField(default=None, max_length=255, null=True, verbose_name='Имя файла OK')),
                ('is_label', models.BooleanField(default=None, null=True, verbose_name='Сформировано содержание этикетки')),
                ('label', models.CharField(default=None, max_length=255, null=True, verbose_name='Содержание этикетки')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('tray_num_task', models.IntegerField(default=0, null=True, verbose_name='tray num за текущую дату')),
            ],
            options={
                'verbose_name': 'Задание на приборе',
                'verbose_name_plural': 'Задания на приборе',
            },
        ),
    ]
