# Generated by Django 3.2.9 on 2024-05-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_incomejson_robo7task'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomejson',
            name='text',
            field=models.TextField(default=None, null=True),
        ),
    ]
