# Generated by Django 4.2 on 2024-08-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_incomejson_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomejson',
            name='is_task_set',
            field=models.BooleanField(default=None, null=True, verbose_name='создан таск'),
        ),
    ]
