# Generated by Django 5.0 on 2025-02-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_incomejson_is_task_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.CharField(max_length=255, verbose_name='Наборы исследований')),
                ('active', models.BooleanField(default=False, verbose_name='Активный набор')),
            ],
            options={
                'verbose_name': 'Набор исследования',
                'verbose_name_plural': 'Наборы исследования',
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField(default=None, null=True, verbose_name='Имя файла')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Содержимое папки DATA',
            },
        ),
        migrations.CreateModel(
            name='TaskJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('is_task_set', models.BooleanField(default=None, null=True, verbose_name='создан таск')),
                ('first_name', models.TextField(default=None, null=True, verbose_name='Имя пациента')),
                ('last_name', models.TextField(default=None, null=True, verbose_name='Фамилия пациента')),
                ('middle_name', models.TextField(default=None, null=True, verbose_name='Отчество пациента')),
                ('analysis_name', models.TextField(default=None, null=True, verbose_name='Наименование исследования')),
                ('analysis_code', models.TextField(default=None, null=True, verbose_name='Код исследования')),
                ('barcode', models.TextField(default=None, null=True, verbose_name='Штрих-код')),
                ('exception_text', models.TextField(default=None, null=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Входящие JSON',
                'verbose_name_plural': 'Входящие JSON',
            },
        ),
        migrations.CreateModel(
            name='TubeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=255, verbose_name='Объем')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('filler', models.CharField(max_length=255, verbose_name='Наполнитель')),
            ],
            options={
                'verbose_name': 'Тип пробирки',
                'verbose_name_plural': 'Виды пробирок',
            },
        ),
        migrations.AlterModelOptions(
            name='incomejson',
            options={'verbose_name': 'Входящие JSON тест', 'verbose_name_plural': 'Входящие JSON тест'},
        ),
        migrations.AlterModelOptions(
            name='robo7task',
            options={'verbose_name': 'Задание для BC ROBO7', 'verbose_name_plural': 'Задания для BC ROBO7'},
        ),
        migrations.AddField(
            model_name='robo7task',
            name='exception_text',
            field=models.TextField(default=None, null=True, verbose_name='Ошибка'),
        ),
        migrations.AddField(
            model_name='robo7task',
            name='queue_num',
            field=models.IntegerField(default=1, null=True, verbose_name='Номер последовательности'),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_name', models.CharField(default='Новый вид исследования', max_length=255, verbose_name='Вид исследования(наименование)')),
                ('analysis_code', models.CharField(default='Новый код исследования', max_length=255, verbose_name='Вид исследования(Код)')),
                ('analysis_name_en', models.CharField(default='name', max_length=255, verbose_name='Для печати (англ)')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.analysisset', verbose_name='Набор исследований')),
                ('tube_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tubetype', verbose_name='Тип пробирки')),
            ],
            options={
                'verbose_name': 'Вид исследования',
                'verbose_name_plural': 'Виды исследований',
            },
        ),
        migrations.CreateModel(
            name='ManualTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('is_task_set', models.BooleanField(default=None, null=True, verbose_name='создан таск')),
                ('first_name', models.TextField(default=None, null=True, verbose_name='Имя пациента')),
                ('last_name', models.TextField(default=None, null=True, verbose_name='Фамилия пациента')),
                ('barcode', models.TextField(default=None, null=True, verbose_name='Штрих-код')),
                ('exception_text', models.TextField(default=None, null=True, verbose_name='Ошибка')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.analysis', verbose_name='Вид исследования')),
            ],
            options={
                'verbose_name': 'Ручная отправка - задания',
                'verbose_name_plural': 'Ручная отправка заданий',
            },
        ),
        migrations.CreateModel(
            name='TrayTube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tray', models.IntegerField(unique=True, verbose_name='Номер лотка')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.analysisset', verbose_name='Набор исследований')),
                ('tube_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tubetype', verbose_name='Тип пробирок')),
            ],
            options={
                'verbose_name': 'Лоток',
                'verbose_name_plural': 'Расположение видов пробирок в лотках',
            },
        ),
    ]
