# Generated by Django 5.0 on 2025-03-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_analysisset_datafile_taskjson_tubetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_type', models.TextField(default=None, null=True, verbose_name='Тип ШК')),
                ('barcode_number', models.TextField(default=None, null=True, verbose_name='Номер ШК')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
