# Generated by Django 4.2.7 on 2023-11-03 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0003_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='configtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadmin.configtype', verbose_name='Типы конфигураций'),
        ),
        migrations.AlterField(
            model_name='configtype',
            name='configtype',
            field=models.CharField(max_length=255, verbose_name='Типы конфигураций'),
        ),
    ]
