# Generated by Django 4.2.7 on 2023-11-06 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0004_alter_config_configtype_alter_configtype_configtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.CharField(max_length=255, verbose_name='Наборы исследований')),
            ],
        ),
        migrations.CreateModel(
            name='TubeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=255, verbose_name='Объем')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('filler', models.CharField(max_length=255, verbose_name='Наполнитель')),
            ],
        ),
        migrations.CreateModel(
            name='TrayTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tray', models.IntegerField(unique=True, verbose_name='Вид исследования')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadmin.analysisset', verbose_name='Набор исследований')),
                ('tube_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadmin.tubetype', verbose_name='Тип пробирок')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_name', models.CharField(max_length=255, verbose_name='Вид исследования')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadmin.analysisset', verbose_name='Набор исследований')),
                ('tube_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadmin.tubetype', verbose_name='Тип пробирки')),
            ],
        ),
    ]
