# Generated by Django 4.2.7 on 2023-11-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0005_analysisset_tubetype_traytube_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование задачи')),
                ('status', models.IntegerField(choices=[(1, 'Running'), (2, 'Stopped'), (3, 'Crashed')], verbose_name='Статус')),
                ('timeupdate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='traytube',
            name='tray',
            field=models.IntegerField(unique=True, verbose_name='Номер лотка'),
        ),
    ]
