# Generated by Django 4.2.7 on 2023-11-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0006_task_alter_traytube_tray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Running'), (2, 'Stopped'), (3, 'Crashed')], default=2, verbose_name='Статус'),
        ),
    ]
