# Generated by Django 3.2.23 on 2023-11-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0007_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robo7Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_fio', models.CharField(max_length=255, verbose_name='ФИО пациента')),
                ('analysis', models.CharField(max_length=255, verbose_name='Наименование вида исследования')),
                ('code', models.CharField(max_length=255, verbose_name='ШК')),
                ('tray_num', models.IntegerField(null=True, verbose_name='Назначенный лоток')),
                ('is_validated', models.BooleanField(default=None, verbose_name='Валидация пройдена')),
                ('is_sent', models.BooleanField(default=None, verbose_name='Отправлено на прибор')),
                ('is_complete', models.BooleanField(default=None, verbose_name='Выполнено')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
        ),
    ]
