# Generated by Django 3.2.23 on 2023-11-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0009_alter_robo7task_tray_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robo7task',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='robo7task',
            name='is_complete',
            field=models.BooleanField(default=None, null=True, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='robo7task',
            name='is_sent',
            field=models.BooleanField(default=None, null=True, verbose_name='Отправлено на прибор'),
        ),
        migrations.AlterField(
            model_name='robo7task',
            name='is_validated',
            field=models.BooleanField(default=None, null=True, verbose_name='Валидация пройдена'),
        ),
        migrations.AlterField(
            model_name='robo7task',
            name='tray_num',
            field=models.IntegerField(default=0, null=True, verbose_name='Назначенный лоток'),
        ),
        migrations.AlterField(
            model_name='robo7task',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
    ]
