# Generated by Django 3.2.23 on 2023-11-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0010_auto_20231124_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='robo7task',
            name='is_tray_assigned',
            field=models.BooleanField(default=None, null=True, verbose_name='Лоток назначен'),
        ),
    ]
