# Generated by Django 3.2.23 on 2023-11-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0011_robo7task_is_tray_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisset',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Лоток назначен'),
        ),
    ]
