# Generated by Django 3.2.23 on 2023-11-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0013_alter_analysisset_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name': 'Вид исследования', 'verbose_name_plural': 'Виды исследований'},
        ),
        migrations.AlterModelOptions(
            name='analysisset',
            options={'verbose_name': 'Набор исследования', 'verbose_name_plural': 'Наборы исследования'},
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AlterModelOptions(
            name='configtype',
            options={'verbose_name': 'Конфигурфция', 'verbose_name_plural': 'Конфигурации'},
        ),
        migrations.AlterModelOptions(
            name='robo7task',
            options={'verbose_name': 'Задание на приборе', 'verbose_name_plural': 'Задания на приборе'},
        ),
        migrations.AlterModelOptions(
            name='traytube',
            options={'verbose_name': 'Лоток', 'verbose_name_plural': 'Расположение видов пробирок в лотках'},
        ),
        migrations.AlterModelOptions(
            name='tubetype',
            options={'verbose_name': 'Тип пробирки', 'verbose_name_plural': 'Виды пробирок'},
        ),
    ]
