# Generated by Django 3.2.23 on 2023-11-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0014_auto_20231125_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='robo7task',
            name='filename',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='robo7task',
            name='is_filename',
            field=models.BooleanField(default=None, null=True, verbose_name='Сформировано имя файла'),
        ),
        migrations.AddField(
            model_name='robo7task',
            name='is_label',
            field=models.BooleanField(default=None, null=True, verbose_name='Сформировано содержание этикетки'),
        ),
        migrations.AddField(
            model_name='robo7task',
            name='label',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Содержание этикетки'),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
