# Generated by Django 3.2.23 on 2024-01-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0015_auto_20231128_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='robo7task',
            name='filenameok',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Имя файла OK'),
        ),
    ]
