# Generated by Django 3.2.23 on 2024-01-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0016_robo7task_filenameok'),
    ]

    operations = [
        migrations.AddField(
            model_name='robo7task',
            name='tray_num_task',
            field=models.IntegerField(default=0, null=True, verbose_name='tray num за текущую дату'),
        ),
    ]
